### ISSUE TITLE
Wartości p w raporcie 8

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-IRT#5]
Albo ja coś nie do końca rozumiem, ale Pan się rąbnął o rząd wielkości sprawdzając, czy wartości p < 0.1. Nie powinno być p< 0.01? A nawet 0.001, czyli dwa rzędy?

**Comment by pikrol** [comment]
Chciałem być tylko postępowy pod względem ewentualnego odrzucania itemów.
Tzn. jakby coś było choć trochę blisko to odrzucić.

pon., 26 lip 2021 o 14:58 gkrajewski ***@***.***> napisał(a):
